config/routes.rb
Rails.application.routes.draw do
  root to: 'employees#index'
  resources :employees do
    collection { post :import }
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
  validates :name, presence: true
  validates :lastname, presence: true
  validates :phone, presence: true, numericality: true,
                        length: { minimum: 10, maximum: 11 },
                        uniqueness: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true,
                        uniqueness: { case_sensitive: false },
                        length: { maximum: 105 },
                        format: { with: VALID_EMAIL_REGEX }
  validates :position, presence: true
  validates :salary, presence: true, numericality: true
  validates :department, presence: true

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      Employee.create! row.to_hash
    end
  end

  def self.to_csv
    headers = %w{ name lastname phone email position salary department }
    CSV.generate(headers: true) do |csv|
      csv << headers

      all.each do |emp|
        csv << emp.attributes.values_at(*headers)
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: %i[ show edit update destroy ]

  def index
    @employees = Employee.all

    respond_to do |format|
      format.html
      format.csv { send_data @employees.to_csv }
    end
  end

  def show
  end

  def new
    @employee = Employee.new
  end

  def edit
  end

  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to employees_path, notice: "Employee was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: "Employee was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: "Employee was successfully destroyed." }
    end
  end

  def import
    if !params[:file]
      redirect_to employees_path, notice: "No file selected"
    else
      Employee.import(params[:file])
      redirect_to employees_path, notice: "Employees data added successfully"
    end
  end

  private
    def set_employee
      @employee = Employee.find(params[:id])
    end

    def employee_params
      params.require(:employee).permit(:name, :lastname, :phone, :email, :position, :salary, :department)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_with(model: employee) do |f| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
        <% employee.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :name %>
    <%= f.text_field :name, placeholder: "Name(s) of the new employee " %>
  </div>
  <div>
    <%= f.label :lastname %>
    <%= f.text_field :lastname, placeholder: "Employee's Lastname " %>
  </div>
  <div>
    <%= f.label :phone %>
    <%= f.telephone_field :phone, placeholder: "Employee's phone number " %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.email_field :email, placeholder: "Employee's email " %>
  </div>
  <div>
    <%= f.label :position %>
    <%= f.text_field :position, placeholder: "Employee's position " %>
  </div>
  <div>
    <%= f.label :salary %>
    <%= f.number_field :salary, placeholder: "Employee's salary " %>
  </div>
  <div>
    <%= f.label :department %>
    <%= f.select :department, ["Accountability", "Finance", "Operations", "Security", "HHRR"], placeholder: "Choose one Dept." %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center">Employees List</h1>

<div class="container mt-4 shadow text-center">
<table class="table table-striped">
  <thead>
    <tr>
    <th>Name</th>
    <th>LastName</th>
    <th>Phone</th>
    <th>Email</th>
    <th>Position</th>
    <th>Salary</th>
    <th>Department</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.name %> </td>
        <td><%= employee.lastname %> </td>
        <td><%= number_to_phone(employee.phone, area_code: true) %> </td>
        <td><%= employee.email %> </td>
        <td><%= employee.position %> </td>
        <td><%= number_to_currency(employee.salary, delimiter: ".", separator: "," ) %> </td>
        <td><%= employee.department %> </td>

        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Delete', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

<div class="d-flex justify-content-center">
<%= link_to 'New Employee', new_employee_path, class: "btn btn-outline-primary mb-4" %>
</div>

<div class="container">
  <h4 class="text-start">Import Data</h4>
    <%= form_tag import_employees_path, multipart: true do %>
      <%= file_field_tag :file %><br>
      <%= submit_tag "Upload data", class: "btn btn-outline-primary btn-lg mt-4 mb-4" %>
    <% end %>
  <h4>Export Data</h4>
    <%= link_to "Export data", "/employees.csv", class: "btn btn-outline-primary btn-lg mt-4" %>
</div>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FormEmployees</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>